const STATES = {
    ACCOUNT_GOT_EXPIRING_POINTS: '_ACCOUNT_GOT_EXPIRING_POINTS',
    ACCOUNT_GOT_BALANCE: '_ACCOUNT_GOT_BALANCE',
    REDEEM_FLIGHT_TICKET: '_REDEEM_FLIGHT_TICKET',
    USE_VOUCHER: '_USE_VOUCHER'
}

module.exports = STATES